spring:
  application:
    name: spring-crud-api
  
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:test_db}
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  security:
    user:
      name: admin
      password: admin

server:
  port: ${PORT:8080}

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:your-super-secret-jwt-key-change-this-in-production}
  expiration: ${JWT_EXPIRES_IN:86400000} # 24 hours in milliseconds

# OpenAPI/Swagger Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /api
    operations-sorter: method
    tags-sorter: alpha
  info:
    title: Spring Boot CRUD API
    description: A simple CRUD API built with Spring Boot and PostgreSQL
    version: 1.0.0
    contact:
      name: API Support
      email: support@example.com

# Logging
logging:
  level:
    com.example.springcrudapi: DEBUG
    org.springframework.security: DEBUG 